name: 'Test Action (Main)'

on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # This job can only run on main since secrets aren't given out to PRs on forks
  test-general:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: ./
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: '123456abcdef'
          # We use a variable instead of a secret here so that CI can run
          # properly on forks.
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          some_other_variable: foobar
          file_name: .env

      - name: Verify envfile
        shell: bash
        run: |
          TEST=$(cat <<-END
          DEBUG=false
          SECRET_KEY=password123
          SOME_API_KEY=123456abcdef
          END
          )
          if [ "$TEST" != "$(cat .env)" ]
          then
            echo "Actual:"
            cat .env
            echo "Expected:"
            echo "$TEST"
            exit 1
          fi
